### PR TITLE
add landing page design link to README.md

### PR DESCRIPTION
**Pull request by kavxprxya**

### CODE REVIEW

**Review by mintbomb27 — CHANGES_REQUESTED** [review]
great job! might go unnoticed for some. Add a new section saying Landing Page, add a full size screenshot of the designs, and then add the figma link. As a description, do add a line saying to contribute to issue #54 , to make this website(make it not boring as this).

**Review by mintbomb27 — CHANGES_REQUESTED** [review]
Hey good progress! I'd like the landing page part to be just before the section [Getting Started Contributing](https://github.com/IEEE-VIT/templa-rs/#getting-started-contributing). And please do add a couple of lines about the landing page that it is not built yet, but only designed, so to start developing this, blah blah...

**Comment by kavxprxya** [comment]
Thanks, got it, will make the changes!

**Review by mintbomb27 — APPROVED** [review]
LGTM!

**Pull request merged**
