### PR TITLE
Add template repository

### PR DESCRIPTION
**Pull request by Devanshi0510**
please add label hacktoberfest-accepted

### CODE REVIEW

**Comment by Mannan-Goyal** [comment]
@Devanshi0510 Can you please add repositories which have individual templates rather than ones which consists of multiple templates in repository. This is because our script clones the repository and not branches individually.

**Comment by Devanshi0510** [comment]
I did the correction pls review

**Comment by Mannan-Goyal** [comment]
@Devanshi0510 Can you please put more relevant tags like hackathon pug etc.?

**Comment by mintbomb27** [comment]
@Devanshi0510 Are you still working on this?

**Pull request merged**
