### PR TITLE
feat: added owner tag to the submodules.json so I can use it for prog…

### PR DESCRIPTION
**Pull request by mooyg**
…res bar

### CODE REVIEW

**Comment by mooyg** [comment]
Did this cause I need owner tag to get the repo size from the github api before hand

**Comment by mintbomb27** [comment]
@mooyg Could you clarify why you can't parse the owner from the Repo URL?

**Comment by mooyg** [comment]
Uh I mean I can write logic for that but why waste time on that when I can just add one more field in json and avoid hassle?

**Comment by Mannan-Goyal** [comment]
@mooyg You don't need to write any parsing logic, you can just take the sub-string from the end of the link and append it to the API URL.
So u can take `IEEE-VIT/templa-rs` from the end of https://github.com/IEEE-VIT/templa-rs/ and append it to https://api.github.com/repos/ to finally make https://api.github.com/repos/IEEE-VIT/templa-rs. It's much more easier for people who add templates & efficient than your current method, I request you to follow this.

**Comment by mooyg** [comment]
Also yo

> @mooyg You don't need to write any parsing logic, you can just take the sub-string from the end of the link and append it to the API URL. So u can take `IEEE-VIT/templa-rs` from the end of https://github.com/IEEE-VIT/templa-rs/ and append it to https://api.github.com/repos/ to finally make https://api.github.com/repos/IEEE-VIT/templa-rs. It's much more easier for people who add templates & efficient than your current method, I request you to follow this.

Ok sure

**Comment by mintbomb27** [comment]
Closing the PR as another implementation of the feature was requested.

**Pull request closed without merging**
